### ISSUE TITLE
Data quality

### ISSUE THREAD

**Issue by ericvergnaud** [open4good/open4goods-light#48]
Hi,

in the context of a proof of context, I have downloaded open4goods-full-gtin-dataset.csv from Nov 21.

First, thanks for making this data publicly available.

However, I noticed some DQ issues.

As an example, consider the following row:
"8414234880420","TAURUS",,"autocuiseur 988042000","1632631065571","ES","0",,,,"SOIN CORPS ET VISAGE>BROSSE NETTOYANTE ; AUTOCUISEUR>COCOTTE ; COCOTTE>MINUTE TAURUS ; AUTOCUISEUR>COCOTTE MINUTE ; FAITOUT>MARMITE ; AUTOCUISEUR>AUTOCUISEUR ; AUTOCUISEUR",

A cocotte-minute is surely not sold in the SOIN CORPS ET VISAGE>BROSSE NETTOYANTE department...
Also COCOTTE>MINUTE TAURUS seems like an error
Finally, whilst dept/ > shelf hierarchy seems clear enough, it's unclear whether standalone values such as AUTOCUISEUR are depts or shelves. Some doc improvements would be welcome.

n.b. I tried to provide the above feedback via the contact form on eco-achat.fr, but it seems the credentials to the SMTP server are no longer valid....

**Comment by GoulvenF** [comment]
Hi,

Thanks for your using and your feedback, and sorry for the late answer. 

Yes, data accuracy on categories is realy not good. It's due to the aggregation mechanism and to the fact that some datasources sometimes provides bat labelings.

There is sadly no plan to fix that quick or soon. But if this project can afford a bit more that maintenance, this would be a great priority.

An option however, if there are some others open databases with accurate categories, we could easily import them as trusted datasource. But not sure it exists.

Regards

**Comment by GoulvenF** [comment]
We are hard re-working on the project, now featuring [nudger.fr](https://nudger.fr).

I close, but feel free to contact us ;)
